version: '3.9'

services:
  redis:
    image: rate-limiter-backend-redis
    build:
      context: .
      dockerfile: Dockerfile.redis
    networks:
      - rate_limiter_network

  rabbitmq:
    image: rate-limiter-backend-rabbitmq
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    networks:
      - rate_limiter_network

  rate_limiter_app:
    image: rate-limiter-backend-app
    build:
      context: .
      dockerfile: Dockerfile.app
    networks:
      - rate_limiter_network
    depends_on:
      - redis
      - rabbitmq
      - postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - rate_limiter_app
    ports:
      - 3000:3000
    networks:
      - rate_limiter_network

  postgres:
    image: rate-limiter-backend-postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    networks:
      - rate_limiter_network
    ports:
      - "5432:5432"

  worker:
    image: rate-limiter-backend-worker
    build:
      context: ./worker/
      dockerfile: Dockerfile.worker
    networks:
      - rate_limiter_network
    depends_on:
      - redis
      - rabbitmq

networks:
  rate_limiter_network:
    name: rate_limiter_network
